import '../../src/app.js'
import '../../src/pages/landing/Landing.js'
import '../../src/pages/about/About.js'
import '../../src/pages/examples/Examples.js'
import '../../src/pages/guide/Guide.js'
import '../../src/pages/news/News.js'
